<?php
// complément de page
// v1.0 by PhA 2019-01-29
?>
			<div id="select_color">
				<table>
                                    <tr>
					<td style="border: 2px red solid;" class="blue" onclick="teinte_change(this, 'blue');"></td>
					<td class="lightskyblue" onclick="teinte_change(this, 'lightskyblue');"></td>
					<td class="gainsboro" onclick="teinte_change(this, 'gainsboro');"></td>
					<td class="orange" onclick="teinte_change(this, 'orange');"></td>
					<td class="indianred" onclick="teinte_change(this, 'indianred');"></td>
                                    </tr><tr>
                                        <td class="darkslategrey" onclick="teinte_change(this, 'darkslategrey');"></td>
                                        <td class="darkolivegreen" onclick="teinte_change(this, 'darkolivegreen');"></td>
                                        <td class="lightsteelblue" onclick="teinte_change(this, 'lightsteelblue');"></td>
                                        <td class="pink" onclick="teinte_change(this, 'pink');"></td>
                                        <td class="lemonchiffon" onclick="teinte_change(this, 'lemonchiffon');"></td>
                                    </tr>
				</table>
			</div>


<?php
/*
                        <div id="select_color">
				<table>
					<tr>
					<td class="blue" onclick="teinte_change(this, 'blue');"></td>
					<td class="white" onclick="teinte_change(this, 'white');"></td>
					<td class="green" onclick="teinte_change(this, 'green');"></td>
					<td class="orange" onclick="teinte_change(this, 'orange');"></td>
					<td class="red" onclick="teinte_change(this, 'red');"></td>
					</tr><tr>
					<td class="pink" onclick="teinte_change(this, 'pink');"></td>
					<td class="cyan" onclick="teinte_change(this, 'cyan');"></td>
					<td class="yellow" onclick="teinte_change(this, 'yellow');"></td>
					<td class="violet" onclick="teinte_change(this, 'violet');"></td>
					<td class="vertClair" onclick="teinte_change(this, 'vertClair');"></td>
					</tr>
				</table>
			</div>
*/
?>
